//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HanbiroDemo", Namespace="http://schemas.datacontract.org/2004/07/localHost")]
    [System.SerializableAttribute()]
    public partial class HanbiroDemo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet HanbiroGetDemoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet HanbiroGetDemo {
            get {
                return this.HanbiroGetDemoField;
            }
            set {
                if ((object.ReferenceEquals(this.HanbiroGetDemoField, value) != true)) {
                    this.HanbiroGetDemoField = value;
                    this.RaisePropertyChanged("HanbiroGetDemo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/HanbiroGetInfo", ReplyAction="http://tempuri.org/IService2/HanbiroGetInfoResponse")]
        DEMO.ServiceReference2.HanbiroDemo HanbiroGetInfo(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/HanbiroGetInfo", ReplyAction="http://tempuri.org/IService2/HanbiroGetInfoResponse")]
        System.Threading.Tasks.Task<DEMO.ServiceReference2.HanbiroDemo> HanbiroGetInfoAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : DEMO.ServiceReference2.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<DEMO.ServiceReference2.IService2>, DEMO.ServiceReference2.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DEMO.ServiceReference2.HanbiroDemo HanbiroGetInfo(string email) {
            return base.Channel.HanbiroGetInfo(email);
        }
        
        public System.Threading.Tasks.Task<DEMO.ServiceReference2.HanbiroDemo> HanbiroGetInfoAsync(string email) {
            return base.Channel.HanbiroGetInfoAsync(email);
        }
    }
}
